eten-tech/aquifer-server

- src/Aquifer.Data/Entities/ResourceContentEntity.cs
- src/Aquifer.Data/Entities/ResourceContentVersionAssignedUserHistoryEntity.cs
- src/Aquifer.Data/Entities/ResourceContentVersionEntity.cs
- src/Aquifer.Data/Migrations/20240822142228_AddMoreSuggestedIndexes.Designer.cs
- src/Aquifer.Data/Migrations/20240822142228_AddMoreSuggestedIndexes.cs
Adds indexes suggested by Azure.
> add more suggested indexes

- src/Aquifer.Data/AquiferDbContext.cs
- src/Aquifer.Data/Entities/IpAddressData.cs
- src/Aquifer.Data/Entities/ResourceContentRequestEntity.cs
- src/Aquifer.Data/Migrations/20240828185812_AddIpAddressDataTable.Designer.cs
- src/Aquifer.Data/Migrations/20240828185812_AddIpAddressDataTable.cs
Also handles migration for removed columns from last deployment.
> Add IpAddressData table

- src/Aquifer.API/Clients/Http/Auth0/Auth0HttpClient.cs
- src/Aquifer.API/Clients/Http/OpenAI/OpenAiHttpClient.cs
- src/Aquifer.API/Program.cs
- src/Aquifer.Common/Aquifer.Common.csproj
- src/Aquifer.Common/Clients/AzureKeyVaultClient.cs
- src/Aquifer.Common/Clients/SendGridClient.cs
- src/Aquifer.Jobs/local.settings.example.json
add SendGridClient with function SendEmail
> Add SendGridClient

- src/Aquifer.API/Endpoints/Bibles/Book/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Bibles/Book/Get/Response.cs
- src/Aquifer.Data/Entities/BibleBookContentEntity.cs
- src/Aquifer.Data/Migrations/20240906205424_MakeTextUrlNullable.Designer.cs
- src/Aquifer.Data/Migrations/20240906205424_MakeTextUrlNullable.cs
Also makes the TextUrl nullable.
> remove remaining TextUrl references from code

- src/Aquifer.API/Endpoints/AI/Translate/Endpoint.cs
Doesn't seem like this would have ever worked, so I don't know what happened originally.
> Fix paragraph chunking in translate

- src/Aquifer.API/Endpoints/Projects/Get/Endpoint.cs
Always use the latest Resource Content Version for a Resource Content when looking up word count and assigned user.
> Fix project's resource contents' count and assigned user when there are no draft resource versions.

- src/Aquifer.Data/Entities/ResourceContentVersionAssignedUserHistoryEntity.cs
- src/Aquifer.Data/Migrations/20240916172518_AddSuggestedIndexToAssignedUserHistory.Designer.cs
- src/Aquifer.Data/Migrations/20240916172518_AddSuggestedIndexToAssignedUserHistory.cs
> add suggested index to assigned user history

- src/Aquifer.Data/Entities/ResourceContentEntity.cs
- src/Aquifer.Data/Migrations/20240920141755_AddResourceContentIndexForPerformance.Designer.cs
- src/Aquifer.Data/Migrations/20240920141755_AddResourceContentIndexForPerformance.cs
Another high impact index suggested by Azure SQL.
> add resource contents table index for performance

- src/Aquifer.API/Common/Constants.cs
- src/Aquifer.API/Endpoints/Resources/Content/CreateTranslation/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/SendForPublisherReview/Community/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/SendForPublisherReview/Community/Request.cs
- src/Aquifer.API/Endpoints/Users/GetSelf/Endpoint.cs
- src/Aquifer.API/Endpoints/Users/GetSelf/Response.cs
These biggest change here was that I decided to add a separate endpoint for the community users to send their work to be reviewed for publishers. Due to the constraints of the user, it made more sense to create the new endpoint rather than modifying the existing `send-for-publisher` endpoint. Also, it was a good exercise in understanding the codebase, EF and FastEndpoints.
> Bib 710 modify view edit page for community reviewer users

- src/Aquifer.Data/EventHandlers/ResourceStatusChangeHandler.cs
If two arrays got items, then two new db context objects would get created. The second one would always get created after a response was sent and then a service db context relied on, which was scoped, would be disposed. So the second would blow up. By only using one, it will hold the scope until the handler is done.
> Only create one new db context in change handler.

- src/Aquifer.API/Services/UserService.cs
Fixes "The Include path 'Company->Users' results in a cycle. Cycles are not allowed in no-tracking queries; either use a tracking query or remove the cycle."
> Use tracking EF queries in user service.

- src/Aquifer.API/Endpoints/Resources/Content/CreateTranslation/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/CreateTranslation/Response.cs
Update `ThrowError` to `SendAsync`
> Update Response to accept message string

- src/Aquifer.API/Endpoints/AI/Translate/Endpoint.cs
I couldn't reproduce the 500 not showing up to the front-end. It may be caused by APIM. I hope this just resolves it anyway, because in my own local apps that do translation it seems like OpenAI is prone to random failures, and I've implemented similar retry logic to get around it. Usually the failures are just a one-off and next try is good.
> Add retry logic to open ai calls

- src/Aquifer.API/Modules/Resources/LanguageResources/LanguageResourcesEndpoints.cs
When passages spanned multiple books the start chapter could be greater than the end chapter.  This updates the calculation of the chapter range to use the first or the last chapter of the requested book instead when this happens.
See https://biblionexusworkspace.slack.com/archives/C0662HZ7RKM/p1729175333040109 for the bug report.
> Limit chapter calculation to only chapters in the given book.

- src/Aquifer.API/Endpoints/Resources/Content/NotApplicable/List/Endpoint.cs
This change was lost during all the PR reviews.
> Changed DisplayName To EnglishDisplay For Language

- src/Aquifer.Jobs/Aquifer.Jobs.csproj
- src/Aquifer.Jobs/Common/Constants.cs
- src/Aquifer.Jobs/Configuration/ConfigurationOptions.cs
- src/Aquifer.Jobs/Managers/SendResourceAssignmentNotifications.cs
- src/Aquifer.Jobs/Program.cs
- src/Aquifer.Jobs/SendNewContentEmails.cs
- src/Aquifer.Jobs/Subscribers/NotificationSubscriber.cs
- src/Aquifer.Jobs/SyncApiRequestStatsToStorageTable.cs
- src/Aquifer.Jobs/SyncCustomEventsToStorageTable.cs
- src/Aquifer.Jobs/SyncPageViewsToStorageTable.cs
- src/Aquifer.Jobs/appsettings.example.json
- src/Aquifer.Jobs/appsettings.json
- src/Aquifer.Jobs/local.settings.example.json
This allows the setting of App Settings from `appSettings.json` and `appSettings.{env}.json` in the Jobs project.
> Bib 788 add appsettings to jobs

- .github/workflows/post-merge-internal-api.yml
- .github/workflows/post-merge-jobs.yml
- .github/workflows/post-merge-public-api.yml
- .github/workflows/pre-merge.yml
- src/Aquifer.AI/Aquifer.AI.csproj
- src/Aquifer.API/Aquifer.API.csproj
- src/Aquifer.Common/Aquifer.Common.csproj
- src/Aquifer.Data/Aquifer.Data.csproj
- src/Aquifer.Jobs/Aquifer.Jobs.csproj
- src/Aquifer.JsEngine/Aquifer.JsEngine.csproj
- src/Aquifer.Migrations/Aquifer.Migrations.csproj
- src/Aquifer.Public.API/Aquifer.Public.API.csproj
- tests/Aquifer.Common.UnitTests/Aquifer.Common.UnitTests.csproj
- tests/Aquifer.JsEngine.UnitTests/Aquifer.JsEngine.UnitTests.csproj
- tests/Aquifer.Public.API.UnitTests/Aquifer.Public.API.UnitTests.csproj
- tests/Directory.Build.props
Jobs can't yet update to .net 9 so I left it on .net 8 and multi-targeted library projects.
> Update to .net 9 and latest NuGet packages.

- src/Aquifer.API/Program.cs
- src/Aquifer.Jobs/Program.cs
- src/Aquifer.Migrations/Program.cs
- src/Aquifer.Public.API/Program.cs
- src/Aquifer.Tiptap/package-lock.json
This should result in slightly better SQL for certain EF queries.  See https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/whatsnew#better-support-for-azure-sql-and-azure-synapse.
> Configure Azure SQL explicitly.

- src/Aquifer.Common/Messages/QueueMessageExtensions.cs
- src/Aquifer.Jobs/Subscribers/EmailMessageSubscriber.cs
- src/Aquifer.Jobs/Subscribers/NotificationMessageSubscriber.cs
- src/Aquifer.Jobs/Subscribers/TrackResourceContentRequestMessageSubscriber.cs
- src/Aquifer.Jobs/Subscribers/TranslationMessageSubscriber.cs
- src/Aquifer.Jobs/host.json
- src/Aquifer.Jobs/local.settings.example.json
* Use a standard exception handling strategy to wrap all queue processing.
* Update `hosts.json` configuration with some better best practices.
* Rename remaining queue functions to end with `MessageSubscriber`.
> Improve jobs configuration.

- src/Aquifer.Common/Messages/QueueClientFactory.cs
I used a lower timeout and lower retry than for the other existing `Retry` policies so as to fail fast for queue operations.
> Add queue client retry policy.

- Directory.Packages.props
- src/Aquifer.Jobs/Aquifer.Jobs.csproj
See https://github.com/microsoft/durabletask-dotnet/issues/148.
> Add workaround to fix Jobs on Mac OS X for Arm64.

- src/Aquifer.Jobs/Subscribers/ResourceContentVersionSimilarityMessageSubscriber.cs
There should not be an error thrown when a machine translation does not exist for a Resource Content Version or Snapshot when an attempt was made to score similarity. There are many resources that are in a working state that are in this situation. Instead, we should log a warning and allow the graceful exit of the scoring job.
> Allow for graceful succeed when no Machine Translation exists

- src/Aquifer.Common/Services/ResourceContentSearchService.cs
This reverts back to SQL similar to what we're running in production for the verse ID filtering strategy using `WHERE (EXISTS ... OR EXISTS ...)`, though production only supports a single `startVerseId` and `endVerseId`.  This PR also supports multiple verse ID ranges.
Testing on my local and in SSMS this is much faster than the multi-join strategy I copied from the `/untranslated` endpoint.
> Use previous WHERE EXISTS with OR strategy for verse ID range filtering.

- src/Aquifer.Jobs/Subscribers/CompressAudioMessageSubscriber.cs
Fixes https://biblionexusworkspace.slack.com/archives/C0662HZ7RKM/p1741201856149819
> Use absolute path for ffmpeg executable in deployed function app.

- src/Aquifer.API/Endpoints/Users/Create/Endpoint.cs
- src/Aquifer.API/Endpoints/Users/Create/Request.cs
- src/Aquifer.API/Endpoints/Users/Create/Validator.cs
This is helpful for creating community reviewers
> Add optional languageId to create user request

- src/Aquifer.Common/Services/Caching/CachingApiKeyService.cs
- src/Aquifer.Common/Services/Caching/CachingLanguageService.cs
- src/Aquifer.Common/Services/Caching/CachingVersificationService.cs
- tests/Aquifer.Common.IntegrationTests/Utilities/VersificationUtilitiesTests.cs
Sliding expiration refreshes the cache duration every time the key is accessed.
> Use absolute expiration for MemoryCache, not sliding expiration.

- src/Aquifer.Jobs/host.json
See https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#iloggert-and-iloggerfactory
> Ensure our code is logging in Jobs.

- src/Aquifer.API/Endpoints/Resources/Search/Request.cs
- src/Aquifer.API/Endpoints/Resources/Search/Validator.cs
- src/Aquifer.Common/Utilities/BibleUtilities.cs
- src/Aquifer.Public.API/Endpoints/Bibles/Alignments/Greek/Request.cs
- src/Aquifer.Public.API/Endpoints/Bibles/Alignments/Greek/Validator.cs
- src/Aquifer.Public.API/Endpoints/Bibles/Texts/Get/Request.cs
- src/Aquifer.Public.API/Endpoints/Bibles/Texts/Get/Validator.cs
- src/Aquifer.Public.API/Endpoints/Languages/AvailableResources/List/Request.cs
- src/Aquifer.Public.API/Endpoints/Languages/AvailableResources/List/Validator.cs
- src/Aquifer.Public.API/Endpoints/Resources/Search/GetResources/Request.cs
- src/Aquifer.Public.API/Endpoints/Resources/Search/GetResources/Validator.cs
I audited all requests and validators with `verse` in them and the other ones should already work correctly.
> Support passing 0 as verse number.

- src/Aquifer.API/Endpoints/Comments/Create/Endpoint.cs
- src/Aquifer.API/Endpoints/Comments/Threads/Create/Endpoint.cs
- src/Aquifer.API/Endpoints/Comments/Update/Endpoint.cs
- src/Aquifer.Data/AquiferDbContext.cs
- src/Aquifer.Data/Entities/CommentEntity.cs
- src/Aquifer.Data/Entities/CommentMentionEntity.cs
- src/Aquifer.Data/Migrations/20250327182608_AddCommentMentionsTable.Designer.cs
- src/Aquifer.Data/Migrations/20250327182608_AddCommentMentionsTable.cs
- src/Aquifer.Data/Services/CommentMentionsUtility.cs
- src/Aquifer.Data/Utilities/CommentMentionsUtility.cs
I didn't add validation that user IDs in mentions are legit; if it does happen then the DB will explode due to an invalid FK and the server will return a 500.  There aren't any scenarios where this should happen in practice, though.
> Update comment endpoints to support user mentions.

- src/Aquifer.API/Endpoints/Notifications/List/Endpoint.cs
The userRole enum should be the int value in the sql query.
> Fix bug leaving comments open

- src/Aquifer.API/Endpoints/Resources/BibleReferences/Create/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/BibleReferences/Delete/Endpoint.cs
Removed Language Barrier From Api
> BIB-905 - Allow Bible Reference Association Update for All Languages 

- .github/workflows/pre-merge.yml
This worked correctly on the PR run:
> Add test results reporting to GitHub Actions.

- .github/workflows/post-merge-well-api.yml
- Aquifer.sln
- Directory.Packages.props
- src/Aquifer.Common/Constants.cs
- src/Aquifer.Data/Entities/ApiKeyEntity.cs
- src/Aquifer.Public.API/OpenApi/ClientGenerationSettings.cs
- src/Aquifer.Public.API/OpenApi/SwaggerDocumentSettings.cs
- src/Aquifer.Public.API/Program.cs
- src/Aquifer.Well.API/Aquifer.Well.API.csproj
- src/Aquifer.Well.API/Configuration/ConfigurationOptions.cs
- src/Aquifer.Well.API/Endpoints/Languages/List/ListLanguagesEndpoint.cs
- src/Aquifer.Well.API/Endpoints/Languages/List/ListLanguagesResponse.cs
- src/Aquifer.Well.API/Helpers/EndpointHelpers.cs
- src/Aquifer.Well.API/Program.cs
- src/Aquifer.Well.API/Properties/launchSettings.json
- src/Aquifer.Well.API/Telemetry/RequestTelemetryInitializer.cs
- src/Aquifer.Well.API/appsettings.example.json
- src/Aquifer.Well.API/appsettings.json
> Initial commit of Well API.

- .github/workflows/post-merge-internal-api.yml
- .github/workflows/post-merge-public-api.yml
I left action.yml alone in case we ever need some similar logic, don't think it hurts anything.
> Remove dev from deploy options

- .github/workflows/pre-merge.yml
- Aquifer.sln
- src/Aquifer.Well.API/Program.cs
- tests/Aquifer.API.IntegrationTests/Endpoints/Bibles/Books/List/EndpointTests.cs
- tests/Aquifer.API.IntegrationTests/Endpoints/Bibles/Texts/Get/EndpointTests.cs
- tests/Aquifer.API.IntegrationTests/Endpoints/Marketing/ParentResourceStatuses/List/EndpointTests.cs
- tests/Aquifer.API.IntegrationTests/Endpoints/Resources/Content/Get/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Bibles/Alignments/Greek/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Bibles/Books/List/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Bibles/List/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Bibles/Texts/Get/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Languages/AvailableResources/List/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Languages/List/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Collections/Get/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Collections/List/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Get/Associations/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Get/AvailableLanguages/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Get/ByLanguage/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Get/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Search/GetResources/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Types/List/EndpointTests.cs
- tests/Aquifer.Public.API.IntegrationTests/Endpoints/Resources/Updates/List/EndpointTests.cs
- tests/Aquifer.Well.API.IntegrationTests/App.cs
- tests/Aquifer.Well.API.IntegrationTests/Aquifer.Well.API.IntegrationTests.csproj
- tests/Aquifer.Well.API.IntegrationTests/ConfigurationOptions.cs
- tests/Aquifer.Well.API.IntegrationTests/Endpoints/Languages/List/ListLanguagesEndpointTests.cs
- tests/Aquifer.Well.API.IntegrationTests/appsettings.example.json
- tests/Aquifer.Well.API.IntegrationTests/appsettings.json
Also, add API Key authentication tests for all API endpoints now that API Key checking is baked into the API instead of in Azure Front Door.
> Add Well API Integration Tests.
