- src/Aquifer.API/Endpoints/Bibles/Book/List/Endpoint.cs
Total verses was looking at the verse count, which will be inaccurate on more dynamic translations
where verses are combined. Instead we should look at the max verse number to know what the total
verses is for that translation+book+chapter.
> make TotalVerses more accurate

- .editorconfig
- .gitattributes
Turns out we weren't using the suggested settings for line endings. This updates our .gitattributes and .editorconfig to the same settings that the EFCore repo uses.
Doesn't change what's in the repo but the advantage is non-Windows diffing tools won't detect false positive changes from line endings.
> fix line ending settings

- .github/actions/deploy-to-env/action.yml
- .github/workflows/post-merge-internal-api.yml
- .github/workflows/post-merge-jobs.yml
- .github/workflows/post-merge-public-api.yml
- .github/workflows/pre-merge.yml
To make builds/deployments fully reproducible and avoid untimely failures this pins all GitHub Action versions.
> pin GitHub Action versions

- src/Aquifer.Data/Migrations/20240909211746_DropTextUrlColumnFromBibleBookContents.Designer.cs
- src/Aquifer.Data/Migrations/20240909211746_DropTextUrlColumnFromBibleBookContents.cs
Usages of this column have been removed and the code deployed in all envs.
> drop TextUrl column from BibleBookContents table

- src/Aquifer.API/Endpoints/Projects/AssignedToSelf/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Projects/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Projects/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Projects/ProjectResourceStatusCounts.cs
This fixes the Projects page load times because it won't pull many thousands of resources for the count. However, it slows down the other two pages generally because they have far fewer resources to pull, so counting in memory was then faster.
I think the broader solution is that the progress bar should lazy load on the page, because that part of the query is what's slowing everything down.
> Fix Projects load time

- src/Aquifer.API/Endpoints/Resources/Content/Get/Endpoint.cs
Fixes situation where the audio file resource content id can be what's linked in Related Content dropdown (which then would load a blank page). This makes sure we load the text resoruce content instead.
> Fix related Content dropdown can link to audio file

- src/Aquifer.API/Endpoints/Resources/Content/Get/Endpoint.cs
Tested locally and in dev. Almost doubles the speed of the endpoint.
Before: 700-1200ms
After: 300-800ms
> force the resources content endpoint main query to be split

- src/Aquifer.API/Endpoints/Projects/AssignedToSelf/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Projects/Create/Endpoint.cs
- src/Aquifer.API/Endpoints/Projects/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Projects/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Projects/Start/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/AssignEditor/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/ReviewPending/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/SendForManagerReview/Endpoint.cs
- src/Aquifer.Data/AquiferDbContext.cs
- src/Aquifer.Data/Entities/ProjectEntity.cs
- src/Aquifer.Data/Entities/ProjectResourceContentEntity.cs
- src/Aquifer.Data/Entities/ResourceContentEntity.cs
- src/Aquifer.Data/EventHandlers/ResourceStatusChangeHandler.cs
- src/Aquifer.Data/Migrations/AquiferDbContextModelSnapshot.cs
This is a larger change that only impacts the admin site's routes, not the Bible well.  It was large in scope because it adds a true `ProjectResourceContent` entity instead of bypassing it in the ORM with configuration.  This addition allows filtering a sub-query on the resources/content/get endpoint to only the resource content ID specified in the request instead of doing large join. 
This change significantly reduces DB execution time of this part of the split query from an original 200-300 ms to < 100 ms for resource content ID `6779` in production.
Loading https://qa.admin.aquifer.bible/resources/4949 and looking at the network tab vs local changes goes from 1 second to 500 ms for fetching resource content data with this change.
> Improve performance of resources/content/get endpoint.

- src/Aquifer.API/Endpoints/Resources/Content/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/ResourceReferences/Create/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/ResourceReferences/Delete/Endpoint.cs
- src/Aquifer.API/Modules/Passages/PassagesModule.cs
- src/Aquifer.Data/AquiferDbContext.cs
- src/Aquifer.Data/Entities/AssociatedResourceEntity.cs
- src/Aquifer.Data/Entities/ResourceEntity.cs
- src/Aquifer.Data/Migrations/20241003205330_AddSuggestedIndexesForAssociatedResourcesAndResources.Designer.cs
- src/Aquifer.Data/Migrations/20241003205330_AddSuggestedIndexesForAssociatedResourcesAndResources.cs
This adds an entity for associated resources as an actual entity class for more control over the `AssociatedResources` table. It does so mainly to allow Azure-suggested indexes to be added. It could potentially help improve performance as well, as we saw with EF-generated `ProjectResourceContents` queries.
> split AssociatedResources into its own entity and add suggested indexes

- src/Aquifer.Data/Entities/BibleVersionWordGroupWordEntity.cs
- src/Aquifer.Data/Migrations/20241004145335_AddMissingIndicesForGreekAlignmentQuery.Designer.cs
- src/Aquifer.Data/Migrations/20241004145335_AddMissingIndicesForGreekAlignmentQuery.cs
- src/Aquifer.Public.API/Endpoints/Bibles/Alignments/Greek/Endpoint.cs
Add missing index needed for [this JOIN](https://github.com/BiblioNexusStudio/aquifer-server/blob/ef30f99f626ae0db2ccb389b1c8ee3fe96760b9f/src/Aquifer.Public.API/Endpoints/Bibles/Alignments/Greek/Endpoint.cs#L249).  It will also benefit the [older endpoint](https://github.com/BiblioNexusStudio/aquifer-server/blob/ef30f99f626ae0db2ccb389b1c8ee3fe96760b9f/src/Aquifer.API/Endpoints/Bibles/Alignments/Greek/Book/Chapter/Endpoint.cs#L23).
> Add missing indices for greek alignment query

- src/Aquifer.Common/Services/Caching/CachingLanguageService.cs
- src/Aquifer.Public.API/Endpoints/Resources/Search/GetResources/Endpoint.cs
- src/Aquifer.Public.API/Program.cs
- src/Aquifer.Public.API/Services/ServiceRegistry.cs
This improves performance of basic query searching by a factor of 2-3.  Most of the improvement is from changing the ordering but removing the language JOIN also shaved off some time.  See comments for details on both of those.  See also https://biblionexusworkspace.slack.com/archives/C05D8BE3KUY/p1728062517872939 for some additional ideas for future improvements.
Some data from QA DB profiling.  Searching for "Christ" (https://qa.api.aquifer.bible/resources/search?languageCode=eng&query=christ&offset=0&limit=100&api-key={apiKey}) takes the following duration:
* Getting the total: 1.012 seconds
* Getting the first 100 results (there are only 31): 3.782 seconds
With these changes applied:
* Getting the total: 0.426 seconds
* Getting the first 100 results (there are only 31): 1.700 seconds
> Improve public API resource search route performance.

- .github/workflows/post-merge-internal-api.yml
- .github/workflows/post-merge-public-api.yml
When a hotfix PR merges it triggers a Post-merge workflow which should allow deploying to a given
env. This was not working because the conditional logic in the deploy jobs wasn't handling the
check_should_deploy job.
> allow hotfix deploys to happen from regular hotfix Post-merge workflow

- src/Aquifer.Public.API/Endpoints/Bibles/Alignments/Greek/Endpoint.cs
I don't think this will change functionality because EF should have only a single open `DbConnection` per instantiation of a `DbContext`.  That said, this is more clear, it avoids a method call into the EF stack, and it enables an easier future refactor to open connections manually outside of EF.
> Pass in same DbConnection.

- Aquifer.sln
- src/Aquifer.API/Program.cs
- src/Aquifer.Common/Aquifer.Common.csproj
- src/Aquifer.Data/Aquifer.Data.csproj
- src/Aquifer.Data/DapperExtensions.cs
- src/Aquifer.Data/StaticLoggerFactory.cs
- src/Aquifer.Public.API/Aquifer.Public.API.csproj
- src/Aquifer.Public.API/Endpoints/Bibles/Alignments/Greek/Endpoint.cs
- src/Aquifer.Public.API/Program.cs
Dapper doesn't build in automatic retries.  This PR adds new "WithRetries" extension methods that we should use instead of the primary Dapper extension methods.  The new methods use the EF Core transient SQL Exception detection and Polly to trigger retries.
> Add Dapper retry overloads.

- src/Aquifer.Jobs/SendNewContentEmails.cs
- src/Aquifer.Jobs/SyncApiRequestStatsToStorageTable.cs
- src/Aquifer.Jobs/SyncCustomEventsToStorageTable.cs
- src/Aquifer.Jobs/SyncPageViewsToStorageTable.cs
Azure is dumb and can't bind `_` (the discard parameter) as a parameter name for a `TimerTrigger` parameter.  But it doesn't let you know this until it blows up at runtime and I missed it amongst the other Job logging when testing my previous PR.  See also https://github.com/Azure/azure-functions-dotnet-worker/issues/323.
Logs:
```
[2024-10-23T20:16:27.939Z] The 'SyncApiRequestStatsToStorageTable' function is in error: The binding name _ is invalid. Please assign a valid name to the binding.
[2024-10-23T20:16:27.940Z] The 'SendNewContentEmails' function is in error: The binding name _ is invalid. Please assign a valid name to the binding.
[2024-10-23T20:16:27.940Z] The 'SyncCustomEventsToStorageTable' function is in error: The binding name _ is invalid. Please assign a valid name to the …
```
> Fix TimerInfo parameter Azure Trigger Function bindings.

- src/Aquifer.Data/Entities/ResourceContentVersionEntity.cs
See https://biblionexusworkspace.slack.com/archives/C0662HZ7RKM/p1729797051412399 for details on why this was breaking.  tl;dr: Don't use `IEnumerable<T>` for EF one-to-many or many-to-many relationships with an assignment of `[]` because that will assign `Array.Empty<T>` under the hood which doesn't support `Add`.
I confirmed this fixes resource assignment and these are the only `IEnumerable<T>` usages like this in the Aquifer.Data project.
> Fix resource assignment.

- src/Aquifer.Jobs/appsettings.example.json
- src/Aquifer.Jobs/appsettings.json
`Aquifer*BaseUri` is not in a sub-class in the [ConfigurationOptions](https://github.com/BiblioNexusStudio/aquifer-server/blob/0fee44288d7c3aef7e233c569159769fe767ad3c/src/Aquifer.Jobs/Configuration/ConfigurationOptions.cs#L7-L8).
> Fix Aquifer BaseUri appsettings.json configuration.

- src/Aquifer.Common/Messages/Models/SendEmailMessage.cs
- src/Aquifer.Common/Messages/Models/SendTemplatedEmailMessage.cs
- src/Aquifer.Jobs/Common/NotificationsHelper.cs
- src/Aquifer.Jobs/Managers/SendResourceAssignmentNotificationsManager.cs
- src/Aquifer.Jobs/Services/SendGridEmailService.cs
- src/Aquifer.Jobs/Subscribers/EmailMessageSubscriber.cs
- src/Aquifer.Jobs/Subscribers/NotificationMessageSubscriber.cs
Changes:
* Notification emails are now sent using the To field instead of the Bcc field.
* Notification emails now use a reply-to address of `no-reply@aquifer.bible` (instead of putting that in the To field).
* Notification emails now also support bulk send with unique personalization content for templated emails.
Additional details:
Initially I was unable to prevent the sending of a single email with multiple recipients in the To field.  I was able to address this by sending multiple personalizations in the SendGrid email, one per To, instead of only one personalization with all of the Tos.  This also allows for unique personalization dynamic template data for each To email address (the third bullet point above). To confirm that this new personalization worked correctly I updated all …
> Refactor notification emails to use unique personalizations and one email per To address.

- src/Aquifer.Common/Clients/Http/IpAddressLookup/IpAddressLookupHttpClient.cs
Add logging to help diagnose alerts like [this](https://biblionexusworkspace.slack.com/archives/C0662HZ7RKM/p1731011332287459).
> Add logging for IP address lookup failures.

- src/Aquifer.Common/Messages/Models/TranslationOrigin.cs
- src/Aquifer.Jobs/Subscribers/TranslationMessageSubscriber.cs
`TranslationOrigin.BasicTranslationOnly` will bypass some validation, will only perform translation and take a snapshot, and will not perform any assignments or make any status changes (unless the original status was AI Draft).
This PR also adds comments to the `TranslationOrigin` values to better document the flow for each origin and handles additional edge cases.
> Support dev scripted translations.

- Aquifer.sln
- Directory.Packages.props
- src/Aquifer.AI/Aquifer.AI.csproj
- src/Aquifer.API/Aquifer.API.csproj
- src/Aquifer.Common/Aquifer.Common.csproj
- src/Aquifer.Data/Aquifer.Data.csproj
- src/Aquifer.Jobs/Aquifer.Jobs.csproj
- src/Aquifer.JsEngine/Aquifer.JsEngine.csproj
- src/Aquifer.Migrations/Aquifer.Migrations.csproj
- src/Aquifer.Public.API/Aquifer.Public.API.csproj
- tests/Directory.Build.props
See https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management.  This has been out for over a year and half and is pretty battle tested by now.
Advantages:
* Both Rider and VS support CPM via their NuGet Package Management UIs.
* Moves NuGet Package Version to a single file in the solution.
* And thus enforces the same NuGet package version across the entire solution.
* But allows overrides for a single project if a different version is needed only for that project.
> Use Central Package Management.

- Directory.Build.props
The build is currently failing with:
```
error NU1903: Warning As Error: Package 'System.Private.Uri' 4.3.0 has a known high severity vulnerability
```
These warnings should remain warnings and should not fail the build because we may not have control over fixing them.
> Downgrade NuGet package security errors to warnings.

- src/Aquifer.AI/OpenAiTranslationService.cs
- src/Aquifer.Jobs/Subscribers/TranslationMessageSubscriber.cs
Translation pairs were swapping out HTML attribute text.  This won't perfectly solve the problem but it will remove all span contents before doing translation pair swaps.
The only way to do it without any risk of messing with HTML would be to parse the HTML using something like HtmlAgilityPack, only do replacements on HTML text content, and then `ToString()` it back to HTML.
> Apply translation pair replacements after minifying HTML.

- src/Aquifer.AI/OpenAiTranslationService.cs
The OpenAI client mutated the `ChatCompletionOptions` singleton passed in by our calling code on every chat completion request and add the chat messages to an `internal` property.  This meant that multiple translation requests could end up using the same chat messages during race conditions resulting in incorrect translations based upon the content or display names of other resources.
> Fix ChatCompletionOptions race condition.

- src/Aquifer.Data/AquiferDbContext.cs
- src/Aquifer.Data/EventHandlers/BadTranslationPairHandler.cs
- src/Aquifer.Data/Exceptions/TranslationPairKeyNotAllowedException.cs
Originally was going to use an interceptor (hence the branch name), but just adding to the saving event was simpler. Noticed that the other method was misnamed, and it runs after the records are already saved (so that was a nice waste of time).
> Add handler for bad translation pair keys

- src/Aquifer.API/Endpoints/Projects/ProjectResourceStatusCounts.cs
- src/Aquifer.API/Endpoints/Resources/Content/AssignedToOwnCompany/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/AssignedToSelf/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/NextUp/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/SendForEditorReview/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/ToAssign/List/Endpoint.cs
Fixed the following places:
- all project resource counts so they show Aquiferize AI drafts as not started
- assigned-to-own-company so the Manage Tab shows AquiferizeAiDraftComplete items
- assigned-to-self so it doesn't show AquiferizeAiDraftComplete items (so managers don't see their to-assign items in My Work)
- send-for-editor-review so it allows assigning AquiferizeAiDraftComplete items
- to-assign so it shows AquiferizeAiDraftComplete so the To Assign tab shows those items
- next-up so it takes into account AquiferizeAiDraftComplete and TranslationAiDraftComplete
> add AquiferizeAiDraftComplete to relevant places

- .github/workflows/pre-merge.yml
- Aquifer.sln
- Directory.Packages.props
- src/Aquifer.Public.API/Program.cs
- tests/Aquifer.Public.API.IntegrationTests/AppFixture.cs
- tests/Aquifer.Public.API.IntegrationTests/Aquifer.Public.API.IntegrationTests.csproj
- tests/Aquifer.Public.API.IntegrationTests/BiblesListTestFixture.cs
- tests/Directory.Build.props
- tests/readme.md
This PR implements integration testing of the Public API via `FastEndpoints.Testing` and `WebApplicationFactory` which create an in-memory API service which uses an `HttpClient` that doesn't actually make any network calls in order to test the `Endpoint`s using the existing `Request` and `Response` objects.
The build server won't pass the tests until we add environment variables as GitHub Secrets for the needed `appsettings.json` overrides (see "Edit Workflow" [here](https://medium.com/@gabreguarnieri/keep-your-keys-safe-while-testing-and-deploying-your-application-414a9e15b32f) for an example).  If I get good feedback on this PR I'll work on adding those.
> Add Public API integration tests.

- .github/workflows/post-merge-jobs.yml
Required configuration changes:
* `GithubActionsDeployDevQaJobs`: `repo:BiblioNexusStudio/aquifer-server:environment:dev-qa-jobs`
* `GithubActionsDeployProdJobs`: `repo:BiblioNexusStudio/aquifer-server:environment:prod-jobs`
> Run DB migrations when deploying Jobs.

- Aquifer.sln
- Directory.Build.props
- Directory.Packages.props
- Directory.Solution.props
- src/Aquifer.Common/Tiptap/TiptapConverter.cs
- src/Aquifer.Common/Utilities/JsonUtilities.cs
- src/Aquifer.JsEngine/Aquifer.JsEngine.csproj
- src/Aquifer.Public.API/Aquifer.Public.API.csproj
- src/Aquifer.Public.API/Endpoints/Bibles/List/Endpoint.cs
- src/Aquifer.Public.API/Endpoints/Bibles/List/Response.cs
- src/Aquifer.Public.API/Endpoints/Resources/Collections/Get/Endpoint.cs
- src/Aquifer.Public.API/Endpoints/Resources/Collections/Get/Response.cs
- src/Aquifer.Public.API/Endpoints/Resources/Get/Request.cs
- src/Aquifer.Public.API/Endpoints/Resources/Get/ResourceHelper.cs
- src/Aquifer.Public.API/Endpoints/Resources/Get/Response.cs
- src/Aquifer.Public.API/Endpoints/Resources/Types/List/Endpoint.cs
- src/Aquifer.Public.API/Endpoints/Resources/Types/List/Response.cs
- src/Aquifer.Public.API/Endpoints/Resources/Updates/List/Endpoint.cs
- src/Aquifer.Public.API/OpenApi/ClientGenerationSettings.cs
- src/Aquifer.Public.API/OpenApi/SwaggerDocumentSettings.cs
- src/Aquifer.Public.API/Program.cs
There are now four new routes under `/docs/index.html?url=/swagger/v1/swagger.json#tag/Clients`, each of which downloads a zip file containing client source code for C#, TypeScript, Python, and Java, respectively.  For example, to download the C# client perform a GET request to `/clients/cs`.
This PR also adds substantial documentation to each of those routes about how to use the client.  The C# documentation is fully featured with a working example including how to inject the API Key into the header of every request; if we like this then examples for other languages could also be added.  See the screenshot below.  We could also consider moving this example into a standalone GitHub repo with examples for each language.
Concerns I found when consuming the generated C# client:
* The current …
> Generate Clients for Public API.

- src/Aquifer.API/Endpoints/Bibles/BibleLicenseInfo.cs
- src/Aquifer.API/Endpoints/Bibles/Language/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Bibles/Language/List/Response.cs
- src/Aquifer.API/Endpoints/Bibles/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Bibles/List/Response.cs
- src/Aquifer.API/Endpoints/Marketing/ParentResourceStatuses/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Marketing/ParentResourceStatuses/List/Response.cs
- src/Aquifer.API/Endpoints/Resources/Content/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/Get/Response.cs
- src/Aquifer.API/Endpoints/Resources/ParentResources/List/Response.cs
- src/Aquifer.API/Endpoints/Resources/ResourceLicenseInfo.cs
- src/Aquifer.Data/Entities/BibleEntity.cs
- src/Aquifer.Data/Entities/ParentResourceEntity.cs
- src/Aquifer.Data/Migrations/20241218214155_Make_LicenseInfo_Nullable.Designer.cs
- src/Aquifer.Data/Migrations/20241218214155_Make_LicenseInfo_Nullable.cs
- src/Aquifer.Public.API/Endpoints/Bibles/BibleLicenseInfo.cs
- src/Aquifer.Public.API/Endpoints/Bibles/List/Endpoint.cs
- src/Aquifer.Public.API/Endpoints/Bibles/List/Response.cs
- src/Aquifer.Public.API/Endpoints/Resources/Collections/Get/Endpoint.cs
- src/Aquifer.Public.API/Endpoints/Resources/Collections/Get/Response.cs
- src/Aquifer.Public.API/Endpoints/Resources/Get/ResourceHelper.cs
- src/Aquifer.Public.API/Endpoints/Resources/Get/Response.cs
- src/Aquifer.Public.API/Endpoints/Resources/ResourceLicenseInfo.cs
- src/Aquifer.Public.API/Endpoints/Resources/Types/List/Endpoint.cs
- src/Aquifer.Public.API/Endpoints/Resources/Types/List/Response.cs
This is a step on the way to using relational DB tables for the license info JSON.  I confirmed that all public API routes match production/QA and the internal API routes all load correctly.  The main difference is that `null`s are now populated:
> Use LicenseInfo strongly typed models and make DB column non-nullable.

- src/Aquifer.Data/AquiferDbContext.cs
- src/Aquifer.Data/Entities/IpAddressData.cs
- src/Aquifer.Data/Entities/IpAddressDataEntity.cs
- src/Aquifer.Data/Migrations/20250106161348_MakeIpAddressColumnsNullable.Designer.cs
- src/Aquifer.Data/Migrations/20250106161348_MakeIpAddressColumnsNullable.cs
- src/Aquifer.Jobs/Program.cs
- src/Aquifer.Jobs/Subscribers/TrackResourceContentRequestMessageSubscriber.cs
- src/Aquifer.Jobs/local.settings.example.json
1. Only allow one simultaneous request to the IP address service for a given IP address.  This is accomplished with DB read row locking because Azure functions don't necessarily share the same memory caching instance so a `MemoryCache`/`HybridCache` won't work and the only other way to do distributed locking would be to stand up a distributed redis cache instance.  Using a DB transaction isn't the most ideal way to lock because the transaction is held open during the duration of the IP address service lookup (including Polly retries with delays) but being that the lock is for a single row (including an empty row) it should be acceptable.
2. Retry with Polly on 429 (Too Many Requests) responses with a delay.
3. Record IP lookup data _even if_ it's null.  Right now we don't record it which …
> Reduce calls to 3rd party IP address service and handle rate limiting.

- src/Aquifer.API/Endpoints/Resources/Content/MachineTranslation/Update/Endpoint.cs
Update endpoint to allow users that have been assigned the resource at all to update machine translation scores.
This resolves the error messages when a user clicks the machine translation score and then the `Send to Review` too quickly.
> Update `/resources/content/machine-translation/{Id}` sql 

- src/Aquifer.API/Endpoints/Bibles/Book/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Bibles/Book/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Bibles/Language/List/Endpoint.cs
- src/Aquifer.Data/Entities/BookEntity.cs
This improves both query performance and correctness by removing unnecessary and incorrect JOINs on BSB chapter count data in `BookChapters` and using the `BibleBookContents.ChapterCount` information instead for the given Bible.
I confirmed that:
1. JSON matches before/after for affected routes.
2. All Bibles in the DB have the same number of chapters for all books, so switching from BSB's chapter counts to the specific Bible's chapter counts (in `BibleBookContents`) should have no consumer impact.  SQL for that:
```
SELECT b1.BibleId, b2.BookId, b1.ChapterCount, b2.ChapterCount
FROM 
(
(SELECT bbc1.BibleId, bbc1.BookId, bbc1.ChapterCount FROM BibleBookContents bbc1) b1
CROSS JOIN
(SELECT bbc2.BibleId, bbc2.BookId, bbc2.ChapterCount FROM BibleBookContents bbc2) b2
)
WHERE
b1.BibleId <> …
```
> Use ChapterCount column instead of counting chapters.

- .github/workflows/post-merge-internal-api.yml
- .github/workflows/post-merge-jobs.yml
- .github/workflows/post-merge-public-api.yml
- .github/workflows/pre-merge.yml
- Aquifer.sln
- global.json
This prevents the build server from using a .net new SDK version without us realizing it while also enforcing that devs are using the same SDK version locally, all from one configuration file.
Note that I allowed patch updates (which seems safe) but we could lock it down to a specific patch version if desired.
> Specify dotnet SDK version in global.json file.

- src/Aquifer.Jobs/host.json
See [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?tabs=isolated-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#host-json).
Note that this impacts _all_ queues, not just the similarity scoring queue.  The translation processing also had some errors when there were many messages so this change seems like an overall improvement.  If we want to only change values for a single queue then we'll either need (a) multiple function apps, each with a unique `host.json` file, or (b) [implement a custom factory](https://stackoverflow.com/a/52638472) to inject our own settings per queue.
> Limit the number of concurrent queue processing operations.

- .github/workflows/pre-merge.yml
- src/Aquifer.API/Common/Permissions.cs
- src/Aquifer.API/Endpoints/Users/List/Endpoint.cs
- src/Aquifer.API/Services/Auth0Service.cs
- tests/Aquifer.API.IntegrationTests/App.cs
- tests/Aquifer.API.IntegrationTests/Aquifer.API.IntegrationTests.csproj
- tests/Aquifer.API.IntegrationTests/ConfigurationOptions.cs
- tests/Aquifer.API.IntegrationTests/Endpoints/Resources/Content/Get/EndpointTests.cs
- tests/Aquifer.API.IntegrationTests/appsettings.example.json
- tests/Aquifer.API.IntegrationTests/appsettings.json
Notes:
* I created a client for each of the CMS roles (leaving out a couple less used roles).  If we want additional roles represented in the future it's easy to add them.
* I wrote code that can create the test users, one per role.  This code will only be run once (I already ran it locally); if a test user exists already (by email lookup) then the existing user will be used for the tests instead of making a new user every test run.
* All test users share the same password.
* In order to create the test users with a known password I used the existing Create User endpoint and then manually updated the password.
* In order to get a bearer token for the test users I created a new Auth0 application which allows authenticated directly with username/password via the [Resource Owner Password …
> Add support for authenticated integration tests.

- .github/actions/deploy-to-env/action.yml
- .github/workflows/post-merge-internal-api.yml
- .github/workflows/post-merge-jobs.yml
- .github/workflows/post-merge-public-api.yml
- Aquifer.sln
With this implementation we will deploy first to East US and then after that succeeds deploy to Central India.  If steps fail it should be possible to re-run each regional deployment independently.  I also added the region name to all deployment Slack notifications for clarity.
Future improvements:
* We could deploy to all regions in parallel if we move the migration script execution into a separate job that runs before deployment.
* [This commit](https://github.com/BiblioNexusStudio/aquifer-server/commit/b946fb00a6d5bb9b8d989bb506c9556e00ca90e5) added a bunch of redundant Git checkout steps.  I'm not sure why (possibly for Slack notifications?).  We could speed up deployments by removing that step.
> Update CI/CD to also deploy the Public API to India.

- .github/actions/deploy-to-env/action.yml
- .github/workflows/post-merge-internal-api.yml
- .github/workflows/post-merge-jobs.yml
- .github/workflows/post-merge-public-api.yml
- .github/workflows/pre-merge.yml
1. Update GitHub Actions action versions to latest for all third-party actions.
2. Stop passing a publish profile for Jobs deployments (per https://github.com/Azure/functions-action?tab=readme-ov-file#use-an-azure-service-principal-not-recommeded).
> Remove publish profile from Jobs deployment.

- .github/workflows/pre-merge.yml
The `Pre-merge / Build and test (pull_request)` job will no longer run for Draft PRs but is still required for merging.  Clicking "Ready for review" will result in the checks running.
Example:
> Don't run pre-merge build and test job for Draft PRs.

- src/Aquifer.Common/Messages/QueueClientFactory.cs
Fixes [this regression](https://github.com/BiblioNexusStudio/aquifer-server/commit/1d4cbc3762804c9f95aad962913b6e3ad7a1d44d#diff-4d5ebc059058589b8a9144dc737b2795d237c8dcdf6edd5592ce138fcd0be8a9L57).
> Pass queue name during queue client construction.

- src/Aquifer.API/Endpoints/Admin/Caches/Clear/Endpoint.cs
- src/Aquifer.API/Endpoints/Admin/Caches/Clear/Request.cs
- src/Aquifer.API/Endpoints/Admin/Caches/Clear/Validator.cs
- src/Aquifer.API/Endpoints/Marketing/ParentResourceStatuses/List/Endpoint.cs
- src/Aquifer.API/Helpers/EndpointHelpers.cs
- src/Aquifer.API/Telemetry/RequestTelemetryInitializer.cs
- src/Aquifer.Common/Constants.cs
- src/Aquifer.Common/Extensions/ServiceCollectionExtensions.cs
- src/Aquifer.Common/Messages/Publishers/ResourceContentRequestTrackingMessagePublisher.cs
- src/Aquifer.Common/Middleware/ApiKeyAuthorizationMiddleware.cs
- src/Aquifer.Common/Services/Caching/CachingApiKeyService.cs
- src/Aquifer.Data/Entities/ApiKeyEntity.cs
- src/Aquifer.Public.API/Endpoints/Admin/Caches/Clear/Endpoint.cs
- src/Aquifer.Public.API/Endpoints/Admin/Caches/Clear/Request.cs
- src/Aquifer.Public.API/Endpoints/Admin/Caches/Clear/Validator.cs
- src/Aquifer.Public.API/Helpers/EndpointHelpers.cs
- src/Aquifer.Public.API/OpenApi/ClientGenerationSettings.cs
- src/Aquifer.Public.API/Telemetry/RequestTelemetryInitializer.cs
- tests/Aquifer.API.IntegrationTests/Endpoints/Marketing/ParentResourceStatuses/List/EndpointTests.cs
I tested and both cache clearing scenarios work as expected on both endpoints.  I also confirmed that the swagger docs do not include the new endpoint and no client code is generated for it in the Public API.  The endpoints are gated by a new Admin ApiKeyScope which, in addition to everything granted by `All`, also grants access to admin routes.
> Add route to clear caches to Aquifer.API and Aquifer.PublicAPI.

- src/Aquifer.API/Endpoints/Bibles/Book/List/Endpoint.cs
- src/Aquifer.API/Endpoints/Bibles/Book/List/Response.cs
- src/Aquifer.API/Endpoints/Bibles/Versification/Endpoint.cs
- src/Aquifer.Common/Services/Caching/CachingVersificationService.cs
- src/Aquifer.Common/Utilities/VersificationUtilities.cs
- src/Aquifer.Data/Entities/BookEntity.cs
- tests/Aquifer.Common.UnitTests/Utilities/VersificationUtilitiesTests.cs
1. Cache the min verse ID for each chapter.  For now it's always 1 based upon DB data but this paves the way for having verse 0 data for Psalms with superscripts. As part of this I factored out some of the new Versifications endpoint into a shared method in the VersificationsUtility.
2. Use the `CachingVersificationService` to populate the max verse ID per chapter for display in the Bible Well's verse selector.  This fixes a bunch of bugs where ENG's max verse number (which was always previously returned) was used instead of the actual Bible's max verse numbers:
* Psalm 3:9 cannot currently be selected in the RSB because ENG only has up to 3:8.
* Revelation 12:18 is shown in the verse picker for the BSB [but displays nothing](https://qa.well.bible/view-content/-/REV012018-012018?tab=Bible) …
> Handle min verses and correctly return the max verse number for Bible chapters to the Bible Well.

- src/Aquifer.API/Endpoints/Notifications/List/Endpoint.cs
- src/Aquifer.Data/Entities/CommentEntity.cs
- src/Aquifer.Data/Entities/CommentMentionEntity.cs
- src/Aquifer.Data/Migrations/20250328151017_AddCommentMentionsIndices.Designer.cs
- src/Aquifer.Data/Migrations/20250328151017_AddCommentMentionsIndices.cs
- src/Aquifer.Data/Migrations/20250328152857_AddUserIdIndexToComment.Designer.cs
- src/Aquifer.Data/Migrations/20250328152857_AddUserIdIndexToComment.cs
Changes:
* Comment mentions result in a notification.
* Participation in a comment thread results in notifications for future comments in that thread.
* Users who were previously assigned the resource content will no longer get notifications for comments.  Only the user actively assigned at the time the comment was made will get a notification.
Unchanged:
* The user who created the comment will never get a notification for that comment.
* Only `ResourceContentVersion`s in the Draft status will show notifications.
Implications:
* If a `ResourceContentVersion` is Published then notifications for any comments while it was in Draft will disappear.
* If a Comment is edited to remove a Mention then the notification for that Mention will disappear.
* If a Comment is edited to add a Mention then …
> Update comment notifications.

- src/Aquifer.Jobs/host.json
Azure Portal uses this logging to populate the Metrics tab:
> Fix Azure Functions display of metrics in Azure Portal.

- tests/Aquifer.API.IntegrationTests/Endpoints/Bibles/Texts/Get/EndpointTests.cs
This test was extracted from a closed PR: https://github.com/BiblioNexusStudio/aquifer-server/pull/701
> Add GET /bibles/{id}/texts integration test.

- global.json
- src/Aquifer.AI/OpenAiTranslationService.cs
- src/Aquifer.API/Endpoints/Marketing/ParentResourceStatuses/BibleBooks/Get/Endpoint.cs
- src/Aquifer.API/Endpoints/Resources/Content/GeneralReportingSummary/Endpoint.cs
- src/Aquifer.Jobs/Managers/SendResourceAssignmentNotificationsManager.cs
- src/Aquifer.Jobs/Services/TranslationProcessors/TranslationProcessingService.cs
We previously were using `9.x` [here](https://github.com/BiblioNexusStudio/aquifer-server/blob/e13ff656b846fb5045c3e3b46c203c6258655d83/.github/workflows/pre-merge.yml#L20) before the introduction of `global.json`.  Using `latestFeature` ([docs](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json)) is the equivalent of `9.0.x`.
We'll want to keep an eye on .net releases because the GHA runner images only have one 9.x version installed and we incur a 30-60 second build time penalty if we download and install a different version.  Switching to `latestFeature` let us use the current version on the GHA runner image but if there is a minor version release we'll need to manually update the `global.json` file.
> Use latest dotnet feature release.

- src/Aquifer.API/Endpoints/Bibles/Versification/Endpoint.cs
- src/Aquifer.Common/Services/Caching/CachingVersificationService.cs
- src/Aquifer.Common/Utilities/VersificationUtilities.cs
- tests/Aquifer.Common.UnitTests/Utilities/VersificationUtilitiesTests.cs
The CMS currently tries to fetch verse 0 mappings so it can handle Psalm superscripts correctly.  Unfortunately, there is no current way to distinguish between when (a) there are no mappings for verse 0 from source -> target and (b) verse 0 doesn't exist in the source Bible.  When this happens the front-end can map to a start verse ID that is greater than an end verse ID:
* `Unexpected versification mapping: sourceStartVerseId: 1019043000; sourceEndVerseId: 1019043001; targetBibleId: 11; targetStartVerseId: 1019043000; targetEndVerseId: 1019042001; languageId: 10`
* [Thread](https://biblionexusworkspace.slack.com/archives/C0662HZ7RKM/p1743600233099929)
* [Repro](https://qa.admin.aquifer.bible/resources/385026)
The only way I could think to solve this bug is to return all versification …
> Fix versifications

- src/Aquifer.API/Endpoints/Resources/Content/Get/Endpoint.cs
Since the snapshots are ordered by descending createdBy, the earliest created snapshot should be at the end of the list. The CMS expects this, and assumes the first snapshot is at the end of all snapshots, displaying it as the source.
So to fix it, add the snapshot to the end of the list instead of the beginning.
> Add first snapshot to the end of the list

- src/Aquifer.API/Endpoints/Projects/Create/Endpoint.cs
- src/Aquifer.Data/Services/ResourceHistoryService.cs
See https://biblionexusworkspace.slack.com/archives/C05K5N7F44Q/p1744137443282489.
Example:
https://qa.admin.aquifer.bible/resources/385220 (English -> Spanish -> Portuguese).
The "Source" snapshot is English, the "{Username} New" snapshot is Spanish (the translation source text), and the newest snapshot is the translation in Portuguese.
> Add original English snapshot when source language is not English.

- README.md
- src/Aquifer.Public.API/OpenApi/SwaggerDocumentSettings.cs
- src/Aquifer.Well.API/Aquifer.Well.API.csproj
- src/Aquifer.Well.API/Endpoints/Languages/List/ListLanguagesEndpoint.cs
- src/Aquifer.Well.API/Endpoints/Languages/List/ListLanguagesResponse.cs
- src/Aquifer.Well.API/Helpers/EndpointHelpers.cs
- src/Aquifer.Well.API/OpenApi/ClientGenerationSettings.cs
- src/Aquifer.Well.API/OpenApi/DefaultParameterOperationProcessor.cs
- src/Aquifer.Well.API/OpenApi/EnumSchemaProcessor.cs
- src/Aquifer.Well.API/OpenApi/SwaggerDocumentSettings.cs
- src/Aquifer.Well.API/Program.cs
Also, fixes regression with latest FastEndpoints update where the OpenAPI spec switched from camelCase properties to PascalCase properties.  JSON is case-sensitive so the Kiota generated client is also case-sensitive and this change broke the generated clients for the Public API (we haven't deployed the regression commit to prod yet).  This PR fixes that only for response properties.  I couldn't figure out request query string parameter casing and opened a FastEndpoints issue: https://github.com/FastEndpoints/FastEndpoints/issues/947.  Technically speaking, PascalCase should be accepted in query strings on the server so there's no breaking change.  I still want to fix it if we get a good answer from them, though.
See https://github.com/BiblioNexusStudio/bible-well/pull/50 for usage.
> Support generating Aquifer.Well.API client code into BibleWell solution.

- src/Aquifer.Public.API/OpenApi/SwaggerDocumentSettings.cs
- src/Aquifer.Public.API/Program.cs
- src/Aquifer.Well.API/OpenApi/SwaggerDocumentSettings.cs
- src/Aquifer.Well.API/Program.cs
It turns out that the ordering of `app.UseOpenAPI()` and `app.UseFastEndpoints()` matters.
See https://github.com/FastEndpoints/FastEndpoints/issues/947 for details.
> Fix OpenAPI spec query param property name casing.

- src/Aquifer.Common/Clients/Http/IpAddressLookup/IpAddressLookupHttpClient.cs
This PR attempts to reduce the verbose and often excessive logging alerts when ip address lookups fail due to too many requests being sent by adding retry delay logic. 
Logging example:
> Unable to fetch IP address information for 105.112.218.79. Response code: TooManyRequests; Response: Too many rapid requests. Please try again in some time or signup for a paid plan at https://ipapi.co/pricing .
> Add retry delay to ip address lookup
